- name: Update repositories cache and install the "figlet" package
  apt:
    name: figlet
    update_cache: yes

- name: Copy file 92-ceros-hello-devops-motd to directory /etc/update-motd.d/ on the target host
  copy:
    src: ../files/92-ceros-hello-devops-motd
    dest: /etc/update-motd.d/92-ceros-hello-devops-motd
    owner: ubuntu
    group: ubuntu
    mode: u+rwx,g+rx,g-w,o+rx,o-w
