#!/usr/bin/env bash
# Author: Chikelue Oji

# 92-ceros-hello-devops-motd
# To be copied to the directory /etc/update-motd.d on the target host.

echo
echo
echo
figlet Hello Ceros DevOps
curl icanhazip.com
echo
echo
echo
