- name: Copy file configure_remote_app_node.sh to directory /home/ubuntu/ on the target host
  copy:
    src: ../files/configure_remote_app_node.sh
    dest: /home/ubuntu/configure_remote_app_node.sh
    owner: ubuntu
    group: ubuntu
    mode: u+rwx,g+rx,g-w,o+rx,o-w

- name: Execute configure_remote_app_node.sh to setup AWS CLI and Docker
  command:  bash /home/ubuntu/configure_remote_app_node.sh