- name:  MOTD Customization
  hosts: ceros-ski-appserver1:ceros-ski-appserver2:ceros-ski-loadbalancer
  gather_facts: no
  become: yes
  roles:
    - motd
  tags:
    - motd

- name:  Docker Configuration (with AWS CLI setup for ECR Access)
  hosts: ceros-ski-appserver1:ceros-ski-appserver2:ceros-ski-loadbalancer
  gather_facts: no
  become: yes
  roles:
    - docker
  tags:
    - docker

- name:  Server Hardening (SSH and Fail2Ban Installation and Configuration)
  hosts: ceros-ski-appserver1:ceros-ski-appserver2:ceros-ski-loadbalancer
  gather_facts: no
  become: yes
  roles:
    - sshd
  tags:
    - sshd

- name:  Nginx Docker Image Pull Setup
  hosts: ceros-ski-loadbalancer
  gather_facts: no
  become: yes
  roles:
    - nginx
  tags:
    - nginx
